### ISSUE TITLE
Queue Messages

### ISSUE THREAD

**Issue by mbpakalin** [SeppPenner/Serilog.Sinks.Telegram#1]
Hello,
Thanks for this awesome project first of all.
I've a problem with sending to telegram, i think i saw somewhere in the telegram docs i saw you can send only 30 messages in 1 second. Is there a queue system in this repo ? Because after a while, telegram blocks the bot and i cant receive any messages.

**Comment by SeppPenner** [comment]
Oh, sorry. I have overseen this. At the moment, there is no queue available.

**Comment by SeppPenner** [comment]
Well, I guess, this is a bug in the sink. I will check this.

**Comment by SeppPenner** [comment]
Should be fixed now with https://github.com/SeppPenner/Serilog.Sinks.Telegram/commit/c2c819c18aa06b5398beccc6e786d46261d04d34 and the option: `sendBatchesAsSingleMessages: false`.
