### ISSUE TITLE
HttpRequestException  on a ASP.NET application

### ISSUE THREAD

**Issue by Nisaba** [SeppPenner/Serilog.Sinks.Telegram#25]
Hello,

The sink works well on a .NET 4.62 desktop project.

But on a ASP.NET 4.62 web application (not MVC), I get this error :
System.Net.Http.HttpRequestException - La demande a été abandonnée : Impossible de créer un canal sécurisé SSL/TLS
(Request was aborted: Unable to create SSL / TLS secure channel)

Thank you for your help

**Comment by nebula2** [comment]
Hello,

can you please provide a minimum reproducable?

**Comment by SeppPenner** [comment]
> Hello,
> 
> can you please provide a minimum reproducable?

I wanted to already ask the same thing... I'm not using NetFramework anymore to be honest. Nearly everything (5 projects remaining or so) is running on Net6.0. I can have a look at it, but I definitely need some more information including a minimum working example as @nebula2 mentioned.

**Comment by SeppPenner** [comment]
I will close this issue now, feel free to re-open it if you have a reproducable example :)
