### ISSUE TITLE
Improve support for spoilers and user mentions

### ISSUE THREAD

**Issue by nebula2** [SeppPenner/Serilog.Sinks.Telegram#26]
if we want to use spoilers or mention a user it is required to set `useCustomHtmlFormatting`  in the options and ensure that we escape everything properly each time that we want to log something.

as documented [here](https://core.telegram.org/bots/api#html-style)

we can for example say `This is a spoiler:<tg-spoiler></tg-spoiler>` or `<a href="tg://user?id={userId}">hello</a>` to mention a user.

it would be nice to 
- either expand [this](
https://github.com/serilog-contrib/Serilog.Sinks.Telegram.Alternative/blob/66ab436b3ae170a545696867c0397ae5000d743b/src/Serilog.Sinks.Telegram.Alternative/Sinks/Telegram/StringExtensions.cs#L23) for default support 
- or the ability to pass a function for custom html formatting so that the consumer can pass a custom logic which will kind of replace the extension method.

I would like to create a pull request for the second option as it provides more flexibility and less effort for maintainence in this repository.

**Comment by SeppPenner** [comment]
If you ask me, the best would be to add both of the options: Extend the default behaviour, but make it possible to set a custom logic from the user code. Or am I missing something that this doesn't make sense?

I will have a look at your pull request soon.

**Comment by SeppPenner** [comment]
The new version containing your changes should be available soon.
