### ISSUE TITLE
appsettings.json minimunLevel not working.

### ISSUE THREAD

**Issue by marce1994** [SeppPenner/Serilog.Sinks.Telegram#3]
Sink minimumLevel not working (appsettings example):

```
{
    "Serilog": {
        "Using": [ "Serilog.Sinks.Telegram" ],
        "MinimumLevel": {
            "Default": "Warning"
        },
        "WriteTo": [
            {
                "Name": "Telegram",
                "Args": {
                    "botToken": "123151488:AAgshf4r373rffsdfOfsdzgfwezfzqwfr7zewE",
                    "chatId": "12345",
                    "minimumLevel": "Warning"
                }
            }
        ]
    }
}
```

I changed it to the following, and it worked

```
"Serilog": {
    "Using": [ "Serilog.Sinks.Telegram" ],
    "MinimumLevel": "Debug",
    "WriteTo": [
      {
        "Name": "Telegram",
        "Args": {
          "botToken": "123123123:dpioufdcbfoikjudfsfnifdugnfpiugnfdspiujhfd",
          "chatId": "123123",
          "restrictedToMinimumLevel": 2
        }
      }
    ]
  }
```

**Comment by SeppPenner** [comment]
Ok, I will check this. Sorry, I somehow don't get notified if someone adds issues in my projects...

**Comment by marce1994** [comment]
Ok, no problem, it's an open-source project, let me know if you need some help.

Thx :)

**Comment by SeppPenner** [comment]
Ah, now I understand the issue, I guess, I have renamed this setting... I will add a hint to the documentation on this. (It's called `restrictedToMinimumLevel` now instead of `minimumLevel`).

**Comment by SeppPenner** [comment]
This is fixed with https://github.com/SeppPenner/Serilog.Sinks.Telegram/commit/7d2aea9fb7f2ad51f6f41efe29e8d9444faa7b65.
