### ISSUE TITLE
Use Web Proxy for Telegram requests

### ISSUE THREAD

**Issue by Albert-the-jit** [SeppPenner/Serilog.Sinks.Telegram#30]
in order to use telegram api we should use Web Proxy but in this state there is no way to config that 

in current state HttpClient create at this state ( [   private readonly HttpClient httpClient = new();](https://github.com/serilog-contrib/Serilog.Sinks.Telegram.Alternative/blob/430d6eb93708d6b5832357cb2ce4759131d6b453/src/Serilog.Sinks.Telegram.Alternative/Sinks/Telegram/Alternative/TelegramClient.cs#L30))

**Comment by Albert-the-jit** [comment]
i think would be nice to expose HttpClient as option just like https://github.com/TelegramBots/Telegram.Bot/blob/ad9dfc27e5df9b37a6f4a465e2eb15d5a42a185b/src/Telegram.Bot/TelegramBotClient.cs#L64

**Comment by SeppPenner** [comment]
Fixed by https://github.com/serilog-contrib/Serilog.Sinks.Telegram.Alternative/pull/31.
