### ISSUE TITLE
Bad Request: message is too long. 400 error.

### ISSUE THREAD

**Issue by devsienko** [SeppPenner/Serilog.Sinks.Telegram#33]
If a message is too long Telegram returns 400 http error and nothing happens. We don't' see any messages in the chat.

**Comment by SeppPenner** [comment]
Nice one :) I will provide a new version soon :)

**Comment by devsienko** [comment]
Thank you, but there is another issue related with this one. It's not a problem to split text to few chunks but Telegram returns 400 if we split it betwee opening and closing html tags. For example we have a big message "<i> ... 6000 symbols message ... </i>" and we split it into two parts "<i> ... 4000 symbol message" and "... 2000 symbols message </i>. I don't know how to do it with a little effort. I just did a small dirty hack , I created a fork and removed <i> tags in the big messages:)

**Comment by SeppPenner** [comment]
> Thank you, but there is another issue related with this one. It's not a problem to split text to few chunks but Telegram returns 400 if we split it betwee opening and closing html tags. For example we have a big message " ... 6000 symbols message ... " and we split it into two parts " ... 4000 symbol message" and "... 2000 symbols message . I don't know how to do it with a little effort. I just did a small dirty hack , I created a fork and removed tags in the big messages:)

Ah ok, I need to check this. Let me just re-open the issue for now to not forget about it.

**Comment by SeppPenner** [comment]
Maybe, we should just throw an error and log to self log and add it as hint for developers to split their messages on their own? Splitting HTML based content properly seems quite difficult.

**Comment by SeppPenner** [comment]
> Maybe, we should just throw an error and log to self log and add it as hint for developers to split their messages on their own? Splitting HTML based content properly seems quite difficult.

This will be my new idea now.
