### ISSUE TITLE
LogEventLevel  is not being respected with Serilog overrides

### ISSUE THREAD

**Issue by zoinkydoink** [SeppPenner/Serilog.Sinks.Telegram#6]
When I have the following:
```
"Serilog": {
    "Using": [ "Serilog.Sinks.Console" ],
    "MinimumLevel": "Information",
    "Override": {
      "Microsoft": "Warning",
      "System": "Error"
    },
    "WriteTo": [
        { "Name": "Console" },
        {
          "Name": "Seq",
          "Args": { "serverUrl": "http://logserver:5341" }
        },
        {
          "Name": "Telegram",
          "Args": {
            "botToken": "id",
            "chatId": "id",
            "restrictedToMinimumLevel": "Information"
          }
        }
      ]
   
    }
```

Telegram Sink should NOT be printing 'Information' level logs from Microsoft as I had defined a override to only show Warnings from Microsoft and Errors from System.

Basically the Telegram Sink should respect the overrides

**Comment by SeppPenner** [comment]
So, this does I thought, that this was fixed with the commit that closed https://github.com/SeppPenner/Serilog.Sinks.Telegram/issues/3 already.

**Comment by zoinkydoink** [comment]
I am not sure if that other but addresses this one. While the restrictToMinimumLevel addresses the issue I am having.

while the new flag works great... but it doesn’t check Serilog overrides

if I set restrictToMinimumLevel to Information
It should print all information and above, but if I have a override that says minimum is Warning for Microsoft and System
It should only print warning from Microsoft packages and system but continue to print Information for other packages/custom code

**Comment by SeppPenner** [comment]
I guess, you're right, this is not addressed yet. I will need to investigate on this more as I don't have an idea yet how this is done in Serilog / should be done in sinks.

**Comment by zoinkydoink** [comment]
I assumed that if I provided the overrides, serilog would be smart enough NOT to send the events if they are already overrides but it seems to pass them to the sinks anyways


________________________________

**Comment by SeppPenner** [comment]
> 
> I assumed that if I provided the overrides, serilog would be smart enough NOT to send the events if they are already overrides but it seems to pass them to the sinks anyways

I'm not sure, maybe the sink is just using it wrong. I will check this.

**Comment by zoinkydoink** [comment]
https://github.com/serilog/serilog/issues/1382

**Comment by SeppPenner** [comment]
Mhm, so this is blocked for now...

**Comment by zoinkydoink** [comment]
I think the SO post mentioned there uses filtering that can be used here but I am not sure


________________________________

**Comment by SeppPenner** [comment]
I would like to wait for this until it's supported natively from Serilog.

The workaround seems to be that users can use on their own I would say: https://stackoverflow.com/questions/62341787/how-can-i-override-serilog-levels-differently-for-different-sinks. I don't want to include it in the sink directly for now, to be honest.

**Comment by SeppPenner** [comment]
I would close this now as Serilog doesn't seem to change something here in the main repository...
